import "oaidl.idl";
import "ocidl.idl";

[uuid("04E88DF6-098F-4AD3-A7C6-0A13F7BDA77B")]
[version(1.0)]
library CppCom
{
	importlib("stdole2.tlb");

	[object, uuid("121C468B-6EC4-48C3-8495-0909E4053398")]
	interface IFoo : IUnknown
	{
		HRESULT Bar();
	};

	[object, uuid("5327560C-D7F2-4FF3-BB2E-17EEE9875F2D"), dual]
	interface IFooLate : IDispatch
	{
		[id(1)]
		HRESULT BarLate();
	};

	[uuid("B7491852-3A2B-4CE9-8ADF-4C1D36EA2379")]
	coclass FooNative
	{
		[default] interface IFoo;
	};

	[uuid("876C4FD9-6F4C-4989-8408-B6443F3305E4")]
	coclass FooWrapper
	{
		[default] interface IFoo;
	};

	[uuid("0F78DDEE-D26B-4CD4-BD4A-A7DC70179D19")]
	coclass FooLate
	{
		[default] interface IFooLate;
	};

	[uuid("D3063D53-9552-4AC6-9ADC-48D5E7EFB046")]
	coclass FooBoth
	{
		[default] interface IFoo;
		interface IFooLate;
	};

	[uuid("389B6F44-C0B7-4B72-A053-AECE97E48B32")]
	coclass FooAggregate
	{
		[default] interface IFoo;
	};
};
